# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  - jupyter_contrib_nbextensions==0.5.1
  # Required until https://github.com/jupyterhub/repo2docker/pull/1196 is merged
  - jupyterhub-singleuser>=3.0,<4.0
  # Set default python version to 3.10 - repo2docker sets it to 3.7 instead by default,
  # which can limit us to older package versions
  - python=3.9.18
  # Everyone wants to use nbgitpuller for everything, so let's do that
  - nbgitpuller=1.1.*
  # cuda-toolkit is required for tensorflow-gpu
  - cudatoolkit=11.2.*
  # cudnn is required for tensorflow-gpu
  - cudnn=8.1.*
  - gstatsim=1.0.* 
  - netcdf4=1.6.*            
  - h5netcdf=1.3.*
  - h5py=3.10.* 
  - keras=2.10.0
  - keras-preprocessing=1.1.*
  - opencv-python=4.9.*
  - numpy=1.26.*
  - matplotlib=3.*
  - matplotlib-inline=0.1.*
  - pandas=2.1.*
  - pip=23.*
  - scikit-learn=1.4.*
  - scikit-gstat=1.0.*
  - scipy=1.11.*
  - seaborn=0.13.*
  - tensorflow=2.10.*
  - tensorflow-estimator=2.10.*
  - tensorboard=2.10.*
  - xarray=2023.12.*
  - urllib3=2.1.*
